### PR TITLE
set different deactivation messages for platforms

### PR DESCRIPTION
**Pull request by cvbrian**
https://cloudveil-tech.monday.com/boards/429392938/pulses/3461516927
I've set up different messages depending on the platform. 

Monday item: #3457093833

### CODE REVIEW

**Comment by cvbrian** [comment]
@dkwiebe I've got the site set up locally but not sure how to set up activations and deactivation requests on it to properly test this. Do you have any tips for doing this?

**Comment by dkwiebe** [comment]
@cvbrian, sorry, missed this one.

**Comment by cvbrian** [comment]
@dkwiebe I've fixed this up so you should be able to merge this now.

**Comment by dkwiebe** [comment]
@cvbrian deployed.

**Pull request merged**
